name: draftea_pokedex
description: This is a technical project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^6.2.1
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0
  responsive_grid_list: ^1.4.1

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  hive_ce_generator: ^1.10.0
  injectable_generator: ^2.9.1
  json_serializable: ^6.11.2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: PokemonHollow
      fonts:
        - asset: assets/fonts/Pokemon Hollow.ttf
    - family: PokemonSolid
      fonts:
        - asset: assets/fonts/Pokemon Solid.ttf
